### ISSUE TITLE
Implement Disk Usage monitoring and take proactive steps to retain maximum functionality

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/platform#108]
Core is completely separated. The security properties declare that even if platform is completely compromised, it should not affect core. As exposed by recent testnet downtime, one problem is handling excessive disk usage. 

## Expected Behavior
In the case of excessively high disk usage, non-core / non-critical services are initially turned off, then if disk usage continues to advance, non-core / non-critical services are removed from the machine. This is done to ensure that core always has sufficient disk space to continue operating.

## Current Behavior
mn-bootstrap will allow any container to use as much disk space as the machine has available.

## Possible Solution
The values given are only examples
Once only 6 GB remain, mn-bootstrap should shutdown all DAPI related services. Once 5 GB remain, mn-boostrap should shutdown all Drive related components. Once only 1.5 GB remain mn-bootstrap should remove all DAPI related containers and their disk space. Once only 1 GB remain mn-bootstrap should remove all Drive related components and their disk space.

**Comment by shumkov** [comment]
@PastaPastaPasta I guess it made sense in case if we run platform on all masternodes. If you think we need this with evonodes please reopen this issue.
