### ISSUE TITLE
Cache wallet data during core chain sync

### ISSUE THREAD

**Issue by thephez** [dashpay/platform#119]
When using the SDK with a mnemonic, cache wallet account information so it is accessible immediately the next time the wallet account is used.

## Expected Behavior

After initial sync for a particular wallet (mnemonic), future syncs would generally use locally cached data rather than syncing the entire chain again.

## Current Behavior

Currently, the libraries underlying the SDK don't provide an option to cache wallet info locally so the entire core chain has to be synced when things like `getWalletAccount()` are run. This is problematic as it can take 5+ minutes on testnet.

## Possible Solution

Get wallet-lib's persistence adapter working in conjunction with the SDK and other libraries (dapi-client?)

## Alternatives Considered

Open to suggestions :slightly_smiling_face: 

## Additional Context

Many of the Readme portal tutorials take 5+ minutes to run on testnet due to syncing the chain on each run (e.g. https://dashplatform.readme.io/docs/tutorial-register-an-identity).

Opening this issue for tracking purposes

**Comment by shumkov** [comment]
Storage adapter is implemented
