### ISSUE TITLE
Read the Tendermint State-Transition blockheight for each document

### ISSUE THREAD

**Issue by ghost** [dashpay/platform#120]
Hi,
i would need information about ST block-number for certain documents already written and also current ST blockheight at dapp runtime.

Example Scenario:
User1 updated one of his documents and it doesnt meet the consensus rules I setup for the dapp anymore. I detect it as revision 2 document and Exclude / Invalidate User1 from further usage. But i need to read the original revision 1 document (that can be read from platform explorer at its original ST creation) to validate past dataset for all other users that interacted with User1.
-> This may be solved with immutable documents later, but there are more use-cases where one want to read old revisions

Here an example from Platform Explorer:
Initial doc: https://pce.cloudwheels.net/#/blocks/29503
Updated doc: https://pce.cloudwheels.net/#/blocks/29505
And i would need a reference from the updated document to the original document at block 29503 to find it fast and efficient

Another Scenario:
I want to link between two contracts (A and B) and need to know exactly if a document from contract B was written after a document in contract A and the other way around. I could use createdAt property, but it would lead to extra processing complexity and time. Having the ST block-number as reference would make things much more cleaner and efficient.

**Comment by shumkov** [comment]
You can use tenderdash RPC or platform explorer but only in case if you trust to these sources (you run them).
