### ISSUE TITLE
bug(dashmate): `dashmate restart -p` fails to restart platform and exits silently

### ISSUE THREAD

**Issue by strophy** [dashpay/platform#1216]
## Expected Behavior

Dashmate should return an error message and not just non-zero return code when an error occurs. 

## Current Behavior

Running `dashmate restart -p` fails to restart platform containers, and exits without error, leaving the containers in a stopped state. It is necessary to run `dashmate stop` to stop all containers, including core (exactly what we were trying to avoid) and then `dashmate start` to successfully effect a restart of platform containers. 
![image](https://github.com/dashpay/platform/assets/32928115/e5f1ad5a-1562-4a81-b610-4804c3a95bc8)

Running in verbose mode shows more useful output, but still fails to restart platform containers:
```
dashmate@hp-masternode-15:~$ dashmate restart -pv
[STARTED] Restarting testnet node
[STARTED] Task without title.
[STARTED] Check node is running
[SUCCESS] Check node is running [0.2s]
[STARTED] Stopping testnet node
[SUCCESS] Stopping testnet node [2s]
[SUCCESS] Task without title. [2s]
[STARTED] Task without title.
[STARTED] Check node is not started
[FAILED] Running services detected. Please ensure all services are stopped for this config before starting
[FAILED] Running services detected. Please ensure all services are stopped for this config before starting
[FAILED] Running services detected. Please ensure all services are stopped for this config before starting
```

## Steps to Reproduce (for bugs)

1. Testnet node, dashmate 0.24.12
2. Run `dashmate restart -p`
3.
4.

## Your Environment

* Version used: 0.24.12
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop, server, or mobile):
* Link to your project:

**Comment by pshenmic** [comment]
Fixed in the https://github.com/dashpay/platform/pull/1186

![image](https://github.com/dashpay/platform/assets/17009187/60e9d3c7-808e-4d39-8e3f-e6b7616cca0f)
