### ISSUE TITLE
bug (?) : dashmate cannot read properties of undefined (reading 'ip') and stops during setup

### ISSUE THREAD

**Issue by qwizzie** [dashpay/platform#1262]
During 'dashmate setup' on a new Ubuntu 20.04.6 LTS deployment i come across error 
'Cannot read properties of undefined (reading 'ip')'.

Evo Node is already registered through DMT. Using 'dashmate setup' with Mainnet - Evolution masternode (4000) - already registered Yes. This error comes right after providing BLS priv key and NodeID to Dashmate.

Firewall setup iaw official server configuration guide for mainnet :

ufw allow ssh/tcp
ufw limit ssh/tcp
ufw allow 9999/tcp
ufw logging on
ufw enable

When i give command 'curl -w "\n" -s https://api.ipify.org/' it does show the correct server external ip address, but Dashmate just does not seem to be able to fetch it / reach it on Mainnet mode during dashmate setup. I previously had also additional ip addresses on this server, but those are currently not activated in Ubuntu 20.04.6 LTS with this new deployment, so Dashmate should only see 1 ip address.

## Expected Behavior
Expect dashmate to find my server external ip address on Mainnet mode during dashmate setup

## Current Behavior
Dashmate does not find my server external ip address on Mainnet mode during dashmate setup. Also some yellow warnings during dashmate installation that are most likely unrelated to this, but could be worth taking a look at (https://www.dash.org/forum/index.php?threads/how-to-create-a-no-fuss-evo-node-in-v19.53899/#post-235524)

## Steps to Reproduce (for bugs)

1. Register Evo Node through Dash Masternode Tool
2. Install dashmate and run dashmate setup
3. Choose Mainnet - Evolution masternode (4000 collateral) - already registered yes
4. Provide dashmate with BLS priv key & NodeID
5. Error emerges (at least with me, could very well be some local problem on my side)

## Your Environment
Ubuntu 20.04.6 LTS (newly deployed !!)
npm 9.8.1 (updated from 8.19.4)
Server according Evo hardware requirements

**Comment by qwizzie** [comment]
config.json file currently shows at the end (with mainnet part) 

     }
        }
      },
      "externalIp": null,
      "network": "mainnet",
      "environment": "production"
    }
  },

I tried changing it into "externalIp": "myipaddress", but then dashmate thinks setup is already finished while having problems starting. So i reverted back to default configuration. 

Is there a way to add my ip address directly through a dashmate command, in case dashmate does not detect my external ip address during dashmate setup ?

**Comment by pshenmic** [comment]
Hey there, @qwizzie! Please, upgrade to the latest version, we just have released a fix today 👍

**Comment by qwizzie** [comment]
issued : npm update -g dashmate (worked, i thought i tried this before)
Issued : dashmate update (failing due to setup not finished) 
Issued new dashmate setup and now it would finally let me enter my ip address.

Dashmate setup looks successfull and i can proceed with dashmate start.
Thanks.
