### ISSUE TITLE
bug(dashmate): dashmate status should handle small window sizes

### ISSUE THREAD

**Issue by pshenmic** [dashpay/platform#1273]
## Expected Behavior

Dashmate status should work properly on any window sizes

## Current Behavior

When your terminal windows is too small, dashmate status command's table render gets broken.
<img width="404" alt="image" src="https://github.com/dashpay/platform/assets/17009187/66b4c755-a486-4695-9bbc-a9b039f27732">

## Additional Context

User from Dash forum reports about this case as he is experience it with default PuTTy settings when he is accessing his node

https://www.dash.org/forum/index.php?threads/how-to-create-a-no-fuss-evo-node-in-v19.53899/post-235545

**Comment by shumkov** [comment]
@pshenmic Is it still actual? How to reproduce?

**Comment by shumkov** [comment]
Please reopen if it's still actual
