### ISSUE TITLE
feat(dashmate): `reset --platform` should work when core containers are still running

### ISSUE THREAD

**Issue by strophy** [dashpay/platform#1297]
## Expected Behavior

I would like to be able to `stop --platform` and then `reset --platform` without affecting core containers

## Current Behavior

`reset --platform` fails when containers are running. I then run `stop --platform` to stop the relevant containers, but the `reset --platform` check still fails, because core containers are still running.
```
platform on  master [$] ❯ yarn workspace dashmate dashmate reset --platform
❯ Reset testnet node
  ✖ Running services detected. Please ensure all services are stopped for this config before starting
  ◼ Remove platform services and associated data
  ◼ Reset dashmate's ephemeral data
platform on  master [$] ❯ yarn workspace dashmate dashmate stop --platform
✔ Check node is running
✔ Stopping testnet node
platform on  master [$] ❯ yarn workspace dashmate dashmate reset --platform
❯ Reset testnet node
  ✖ Running services detected. Please ensure all services are stopped for this config before starting
  ◼ Remove platform services and associated data
  ◼ Reset dashmate's ephemeral data
```

## Possible Solution

Adjust running container checks

**Comment by pshenmic** [comment]
I think that relates to https://github.com/dashpay/platform/issues/1291, which I am fixing in the https://github.com/dashpay/platform/pull/1287

**Comment by pshenmic** [comment]
https://github.com/dashpay/platform/pull/1287
