### ISSUE TITLE
(bug) dashmate : does not seem to be able to fetch Dashmate v0.24.20 and will not start Dashmate

### ISSUE THREAD

**Issue by qwizzie** [dashpay/platform#1303]
After stopping my Dashmate with command dashmate stop and then provide commands npm update -g dashmate 
& dashmate update, Dashmate gives following error  : 

Error: (HTTP code 404) unexpected - manifest for dashpay/dashmate-helper:0.24.20 not found: manifest unknown: manifest unknown

Same error when i then try to issue dashmate start. 

## Expected Behavior
Dashmate  should just show in dashmate update that it updated to Dashmate v0.24.20 successfully

## Current Behavior
Throws error and won't allow dashmate start

Current config.json shows at very start

{
"configFormatVersion": "0.24.20",
"defaultConfigName": "mainnet",
"defaultGroupName": null,
"configs": {
"base": {
"description": "base config for use as template",
"group": null,
"docker": {
"network": {
"subnet": "0.0.0.0/0",
"bindIp": "0.0.0.0"
},

## Possible Solution

If Dashmate itself is also updated through Docker, then maybe the solution is uploading v0.24.20 tag here --> https://hub.docker.com/r/dashpay/dashmate-helper/tags ? Latest version there seems to be still v0.24.19

See also forum : https://www.dash.org/forum/index.php?threads/dashmate-discussion.53951/#post-235667

## Steps to Reproduce (for bugs)

* While on Dashmate v0.24.19 issue dashmate stop
* Issue npm update -g dashmate
* Issue dashmate update

I tried installing dashmate again through command npm install -g dashmate and then update it again with command npm update -g dashmate --> same error & same problem (will not allow dashmate start).

I tried installing dashmate again through command npm install -g dashmate, without issuing npm update -g dashmate (hoping that would get me to an older Dashmate version) --> same error & same problem (will not allow dashmate start).

This needs urgent attention, as i can not start dashmate right now due to this error.

**Comment by pshenmic** [comment]
Dashmate v0.24.21 is released that fixes this error
