### ISSUE TITLE
feat(release): release npm package after docker

### ISSUE THREAD

**Issue by pshenmic** [dashpay/platform#1309]
## Expected Behavior

Dashmate (and possibly other) is dependent on successful platform release, and should happen after successful build of our packages

## Current Behavior

If one of the packages fails to build and push to docker, dashmate package still will be released

## Possible Solution

Change the order in the Github Actions, so releasing npm packages happens after releasing docker images is done

**Comment by shumkov** [comment]
Hello! Thank you for your report. Unfortunately, this is a chicken and egg problem. We building docker images and NPM packages in parallel. Either on of the jobs fails another one will be released. Not sure we can do anything here.
