### ISSUE TITLE
bug(dashmate): `config set <key> null` sets to string value of "null"

### ISSUE THREAD

**Issue by strophy** [dashpay/platform#1343]
## Expected Behavior

Running `dashmate config set platform.dapi.envoy.ssl.providerConfigs.zerossl.id null` should set the value to a JSON `null` as defined in the schema.

## Current Behavior

Instead, somehow it gets set to the string `"null"` instead, breaking dashmate on next run.

```
dashmate@hp-masternode-17:~$ dashmate config set platform.dapi.envoy.ssl.providerConfigs.zerossl.id null
platform.dapi.envoy.ssl.providerConfigs.zerossl.id set to null

dashmate@hp-masternode-17:~$ dashmate config get platform.dapi.envoy.ssl.providerConfigs.zerossl.id
    InvalidConfigFileFormatError: Invalid 
    '/home/dashmate/.dashmate/config.json' config format: co
    nfig/platform/dapi/envoy/ssl/providerConfigs/zerossl/id 
    must NOT have fewer than 32 characters
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Trying to set ZeroSSL API key ID in deploy tool to avoid incorrectly indicating the template changed
https://github.com/dashpay/dash-network-deploy/pull/537

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop, server, or mobile):
* Link to your project:

**Comment by shumkov** [comment]
This is fixed.
