### ISSUE TITLE
DAPI: Calls to `getTransaction` only valid if wallet is loaded

### ISSUE THREAD

**Issue by kxcd** [dashpay/platform#1440]
https://github.com/dashpay/platform/blob/ed354ca52969676f8231765fc04bbe02b1d9ba25/packages/dapi/lib/externalApis/dashcore/rpc.js#L174-L193

Where is is this getting called?  A masternode does not have an attached wallet, so calling this on an MN will return the empty set and an error.  IMO these two methods should be removed.

**Comment by shumkov** [comment]
Hello. Thank you for your report. This function is not used. It will be removed when we refactor DAPI.
