### ISSUE TITLE
DAPI: Calls to non-existant RPC `getuser`

### ISSUE THREAD

**Issue by kxcd** [dashpay/platform#1441]
https://github.com/dashpay/platform/blob/ed354ca52969676f8231765fc04bbe02b1d9ba25/packages/dapi/lib/externalApis/dashcore/rpc.js#L195-L203

This is not a valid RPC, this should be removed.

**Comment by shumkov** [comment]
Hello. Thank you for your report. This function is not used. It will be removed when we refactor DAPI.
