### ISSUE TITLE
DAPI: Call to `sendrawtransaction` duplicated for redundant specific case

### ISSUE THREAD

**Issue by kxcd** [dashpay/platform#1443]
https://github.com/dashpay/platform/blob/ed354ca52969676f8231765fc04bbe02b1d9ba25/packages/dapi/lib/externalApis/dashcore/rpc.js#L271C1-L280C1

This method should be deleted, all transactions posted to the Dash network are automatically InstantSend (IX), the parameter set in this version is simply ignored by Dash Core.

**Comment by shumkov** [comment]
Hello! Thank you for your report. It's not using, atm. We will remove it when we refactor DAPI.
