### ISSUE TITLE
DAPI: Remove additional indexes, the default masternode indexes are sufficient

### ISSUE THREAD

**Issue by kxcd** [dashpay/platform#1445]
https://github.com/dashpay/platform/blob/ed354ca52969676f8231765fc04bbe02b1d9ba25/packages/dapi/doc/dependencies_configs/dash.conf#L8-L12

and

https://github.com/dashpay/platform/blob/ed354ca52969676f8231765fc04bbe02b1d9ba25/packages/dashmate/templates/core/dash.conf.dot#L39-L44

These indexes are NOT required for Masternodes aka EvoNodes running platform, two observations.

1. A Masternode does not run a wallet at the same time, this is intentionally not a possible configuration.
2. None of the RPCs (and I checked them all) require any special indices and the one that does `getaddressutxos` is for nodes running wallets, refer to 1.

**Comment by shumkov** [comment]
It's done
