### ISSUE TITLE
feat(dashmate): allow custom folders as datadir storage

### ISSUE THREAD

**Issue by pshenmic** [dashpay/platform#1525]
## Expected Behavior

Users should be able to choose where to keep all the sync data on the disk. Users may have smaller boot disk size and separate larger disks for the storage puproses.

## Current Behavior

Dashmate service's datadirs are mounted as docker volumes (default path /var/lib/docker/volumes)

## Possible Solution

Add a config or dashmate command to override that (set bind mount instead of volume)

**Comment by shumkov** [comment]
https://tienbm90.medium.com/how-to-change-docker-root-data-directory-89a39be1a70b
