### ISSUE TITLE
`yarn setup` Config with name 'local_seed' is not present

### ISSUE THREAD

**Issue by coolaj86** [dashpay/platform#1536]
After overcoming #1535 I get a success / failed about ENVs not being set?

Not sure if this is a real error, or just noise.

```sh
yarn setup
```

```text
# ...
success ✨ Done in 87.337s
platform.drive.abci.docker.build.enabled set to true
platform.dapi.api.docker.build.enabled set to true
dashmate.helper.docker.build.enabled set to true
platform.drive.tenderdash.consensus.createEmptyBlocksInterval set to 10s
platform.drive.abci.logs.stdout.level set to trace
[STARTED] System requirements
[FAILED] Docker is not installed. Please follow instructions https://docs.docker.com/engine/install/
Mint 100 Dash to faucet address
    ConfigIsNotPresentError: Config with name 'local_seed' is not present
Internal error. Some of the env variables are empty. Please check logs above.
```

**Comment by pshenmic** [comment]
The error a bit upper:
```
[FAILED] Docker is not installed. Please follow instructions https://docs.docker.com/engine/install/
```

**Comment by coolaj86** [comment]
What does it need docker for in this case?

How can I skip past it?

**Comment by pshenmic** [comment]
You can't do yarn setup without docker, because it is meant to setup a local regtest environment on your computer, consisting of 4 nodes (seed + 3 evonodes), that simulates a network with platform quorums. I'm not sure you can do this without Docker right now

**Comment by coolaj86** [comment]
1. How do I run it on testnet?
2. How do I  run a seed node? \
   (is that a masternode?)
3. How do I run an evo node?

Spinning up 7 nodes is not a problem. I don't need dicker for that because I don't need to do it on just one computer.

**Comment by pshenmic** [comment]
The only supported environment is Docker for now, and all developers are writing, test and release in Docker, however going standalone isn't impossible. 

You will need to:
* Create a regtest network of 3 hpmn masternodes (running all platform daemons), and 1 seed node (tenderdash + dashcore)
* Register each of your evonodes in your network
* Ensure that network is functioning and wait for all required quorums to come up (+ chainlocks)  

Once there are enough quorums and initial platform start height, drive + tenderdash should initiate an initChain and begin producing platform blocks.

I suggest you to go with Docker first, once you get it on one host, you'll have a chance to peek it and repeat everything separately. There is a lot of bootstrap code to initialize network in the dashmate, all collaterals, and other necessary stuff.
