### ISSUE TITLE
bug(dashmate): Dashmate v0.25.15 & v0.25.16-rc.1+rc.2 on Mainnet -> error + interfering with dashmate status and stop commands

### ISSUE THREAD

**Issue by qwizzie** [dashpay/platform#1583]
Evonode 1 (Ubuntu 20.04.6 LTS / Node v21.2.0 / NPM v10.2.4) 
Edit : later downgraded to Node v20.10.0, same problem

Updated Dashmate from v0.25.13 to v0.25.15 and through manual command (dashmate config set core.docker.image dashpay/dashd:20.0.0) started Core v20.
Dashmate had no problem starting Core v20, but gives error with Dashmate status and dashmate stop commands 

`CompileError: WebAssembly.Module(): Compiling function #331:"memchr::arch::wasm32::simd128:: packedpair::Find..." failed: Wasm SIMD unsupported @+1956688
`

Evonode 2  (Ubuntu 20.04.6 LTS / Node v21.2.0 / NPM v10.2.4)
Edit : later downgraded to Node v20.10.0, same problem

Updated Dashmate from v0.25.13 to v0.25.15 and gave dashmate a start command for v19.3 (this was just a dashmate update, i was already running Core v19.3 on this node, but with Dashmate v0.25.13
Dashmate had no problem starting Core v19.3, but gives error with Dashmate status and dashmate stop commands 

`CompileError: WebAssembly.Module(): Compiling function #331:"memchr::arch::wasm32::simd128:: packedpair::Find..." failed: Wasm SIMD unsupported @+1956688
`

See : https://www.dash.org/forum/index.php?threads/dashmate-discussion.53951/page-3#post-236933

**Comment by qwizzie** [comment]
Reverted back to Dashmate v0.25.13 by issueing 'npm install -g [dashmate@0.25.13](mailto:dashmate@0.25.13)' & 'dashmate update'. 

Both of them got PoSe scored (2200+), i suspect because of the faulty Dashmate version.

**Comment by qwizzie** [comment]
Issue seems related to Node.JS version. Dashmate v0.25.13 had no problem with Node.JS v20.8.0 
Dashmate does seem to run into problems, when coming across Node.JS v21.2.0
(at least with Dashmate v0.25.15)

Solution : either have users limit Node.JS to v20.8.0 or have users limit Node.JS to v18

Pshenmic mentioned following code for reverting Node.JS to v18 : 

nvm install 18
nvm use 18

**Comment by qwizzie** [comment]
See : https://www.dash.org/forum/index.php?threads/dashmate-discussion.53951/page-3#post-236976

nvm install 20
nvm alias default 20
nvm use 20
npm install -g dashmate@0.25.16-rc.1

$ nvm install 20
Downloading and installing node v20.9.0...
Downloading https://nodejs.org/dist/v20.9.0/node-v20.9.0-linux-x64.tar.xz...
############################################################################################################################################################################################################ 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v20.9.0 (npm v10.1.0)
$ nvm alias default 20
default -> 20 (-> v20.9.0)
$ nvm use 20
Now using node v20.9.0 (npm v10.1.0)
npm install -g [dashmate@0.25.16-rc.1](mailto:dashmate@0.25.16-rc.1)

added 664 packages in 37s

113 packages are looking for funding
run `npm fund` for details
$ dashmate update

CompileError: WebAssembly.Module(): Compiling function #1302:"bytecount::simd::wasm::chunk_num_chars::he46d9f..." failed: Wasm SIMD unsupported @+2532414

Exact same error i had with Dashmate v0.25.15

**Comment by pshenmic** [comment]
https://github.com/dashpay/platform/pull/1591

**Comment by pshenmic** [comment]
According @qwizzie report on the Dash Forum, the issue happens on the Ubuntu 22.04 x86_64 with the given CPU:
```
$lscpu

Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
Address sizes: 44 bits physical, 48 bits virtual
CPU(s): 8
On-line CPU(s) list: 0-7
Thread(s) per core: 1
Core(s) per socket: 8
Socket(s): 1
NUMA node(s): 1
Vendor ID: GenuineIntel
CPU family: 6
Model: 85
Model name: Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz
Stepping: 4
CPU MHz: 2992.972
BogoMIPS: 5985.94
Hypervisor vendor: Microsoft
Virtualization type: full
L1d cache: 256 KiB
L1i cache: 256 KiB
L2 cache: 8 MiB
L3 cache: 198 MiB
NUMA node0 CPU(s): 0-7
```

**Comment by qwizzie** [comment]
Actually my OS is Ubuntu **20**.04.6 LTS / GNU/Linux 5.4.0-166-generic x86_64

**Comment by qwizzie** [comment]
Dashmate v0.25.16-rc.6 fixed my problem.
Issue solved.
