### ISSUE TITLE
bug(dpp): WASM DPP bundle doubled in size

### ISSUE THREAD

**Issue by pshenmic** [dashpay/platform#1626]
## Expected Behavior

WASM DPP shouldn't weight too much to be able to easily include in Browser & Mobile environments.

## Current Behavior

WASM DPP JS bundle recently raised in size at least twice from 12 MB to 30 MB, and including all sourcemaps the final Dash SDK bundle raised to unbelievable 72 MB. This is not acceptable for a browser environment as it is drastically increases page load times.

<img width="418" alt="image" src="https://github.com/dashpay/platform/assets/17009187/ca911e63-1ae9-4fa5-9612-117b011bac54">

## Possible Solution

Revise changes between 0.25.13 and 0.25.15 releases, and make more optimization and cut unncessary stuff. Also, might be a good idea to disable wasm dpp source maps

## Context

That happened on 0.25.15 release, because 0.25.13 JS bundle weights about twice less.

**Comment by coolaj86** [comment]
I'm seeing 9.1M which is just mind-blowingly HUGE.

What's going on here? What does this thing even do?

Why not use the modern, native js Dash Incubator libraries? Is there something that they don't support yet that has to be included? If so, how about we just fix the Dash Incubator libs to have the necessary functionality?

https://github.com/dashhive/dash-tools

**Comment by riongull** [comment]
@coolaj86, I spoke about this size issue in our last Incubator quarterly call. Our plan is to add Dash Platform support in our tools, so that will be an issue for our repos. DCG can feel free to close this issue if they don't see an issue in their tools.

**Comment by kxcd** [comment]
Does it cache?  If so, it is not such a big deal.

**Comment by shumkov** [comment]
We are going to rebuild SDK and binding soon so I don't think this problem will be actual. Please reopen otherwise.
