### ISSUE TITLE
feat(dashmate): warn user if the node is participating in DKG sessions

### ISSUE THREAD

**Issue by pshenmic** [dashpay/platform#1648]
## Expected Behavior

Warn user if masternode is participating or going to participate in the DKG session soon when user want to stop or restart the node

## Current Behavior

If user restart core service during DKG session, it will likely receive a POSE ban. We should warn the user about that so that he would choose different restart time window

## Possible Solution

We can calculate time window with the given formula:
<img width="705" alt="image" src="https://github.com/dashpay/platform/assets/17009187/dd0f1d80-6bc9-45eb-8bff-cf3e0cc6c140">

**Comment by qwizzie** [comment]
dashmate core cli 'quorum memberof protxhash 1' looks to be working too. 
For one of my Evonodes it got me the following info 

[
  {
    "height": 1994688,
    "type": "llmq_400_85",
    "quorumHash": "000000000000002a53ea06c15f70cae721df535248b57e2309bfd5a804db308d",
    "quorumIndex": 0,
    "minedBlock": "0000000000000016120c7ea58eb08c7f94c1cc8d65bc05f62b0714a767af3f89",
    "quorumPublicKey": "ae91eb264b4cf80393c263abdfaf78120c4e3526d009b8de0b59a2121ea736bd6ba2934fdd6049b74bc9215164d2a690",
    "isValidMember": true,
    "memberIndex": 95
  },
  {
    "height": 1994832,
    "type": "llmq_100_67",
    "quorumHash": "0000000000000021220668e034d3fb1820cde45a7d5b888955a9df08b7ee8698",
    "quorumIndex": 0,
    "minedBlock": "00000000000000133dc849c9256709d8e09d0fe139b9882cc97efab6341ef702",
    "quorumPublicKey": "80aa22fd2b772e9af977d7d230ad48519bdbbf2a8db3e0201aa5ef1d0665c68f82c16f96c4e11fbbd56d91a8365053f1",
    "isValidMember": true,
    "memberIndex": 20
  }
]

So two quorum involvements currently (llmq 400_85 & llmq 100_67).

**Comment by pshenmic** [comment]
@qwizzie 

Unfortunately, udjin says that it only shows mined DKG windows, in other words that alread have passed

**Comment by knst** [comment]
> Warn user if masternode is participating or going to participate in the DKG session soon when user want to stop or restart the node

> Unfortunately, udjin says that it only shows mined DKG windows, in other words that alread have passed

@pshenmic does it mean that we still can warn user if masternode _is participating_ in the current DKG session (but not future)?

**Comment by qwizzie** [comment]
![Knipsel](https://github.com/dashpay/platform/assets/6610543/6c515f01-b2dd-407b-b897-91fc336ce3aa)

I guess we will need a new type of RPC that Dashmate can use to check if a specific Masternode / Evonode is currently involved in LLMQ_50_60, LLMQ_100_67, LLMQ_60_75 

I am not sure if LLMQ_400_60 is involved with high PoSe Penalty DKG scores, UdjinM6 mentioned (/24)*24 & (/288)*288 so that could also include LLMQ_400_60, but that LLMQ has a lot higher quorumDkgBadVotesThreshold.

**Comment by qwizzie** [comment]
Interim solution : https://www.dash.org/forum/index.php?threads/llmq-pose-check-on-your-evonode-or-masternode-setup-through-dashmate.54445/#post-237453
