### ISSUE TITLE
Rename repository to dash-drive

### ISSUE THREAD

**Issue by coolaj86** [dashpay/platform#1695]
It's very confusing that this is called `platform` because it leads one to think that this is specifically an evo node or the core of evo. However, it's really just the storage component.

Please rename this to `dash-drive` to avoid confusion with "platform" and "evo" as the terms are used generically in the community.

**Comment by shumkov** [comment]
Hello! Thank you for your opinion but I do not agree with the statement that it's just a storage component in this repository. There are many other libraries and components, such as DAPI, SDK, dashmate, contracts, etc.
