### ISSUE TITLE
bug: tenderdash abci version mismatch between tenderdash, rs-tenderdash, and rs-drive-abci  (v0.24 vs v0.25)

### ISSUE THREAD

**Issue by coolaj86** [dashpay/platform#1701]
See <https://github.com/dashpay/platform/pull/1700>.

## Expected Behavior

`tenderdash` should be able to communicate with `drive-abci`.

## Current Behavior

`tenderdash` receives a version mismatch error from `drive-abci` where `drive-abci` claims that its `rs-tenderdash-abci` version is `0.24.0`, but `tenderdash` needs abci version `0.25.0`.

## Possible Solution

Not sure.

I think that perhaps `rs-tenderdash-abci` or `rs-drive-abci` were committed with old `protoc`-generated files.

## Steps to Reproduce (for bugs)

1. Build and start dash-drive as per https://github.com/dashpay/platform/issues/1696
2. Build and start tenderdash as per https://github.com/dashpay/tenderdash/issues/739

The steps above are based on https://docs.dash.org/en/stable/docs/user/masternodes/setup-testnet.html#drive, but with corrections.

## Context

I can't get to the point of testing an Evo Node because I can't get the last few pieces together.

## Your Environment

Latest default branches of tenderdash and platform repos, as of today.

**Comment by coolaj86** [comment]
May be related to https://github.com/dashpay/rs-tenderdash-abci/pull/49

**Comment by lklimek** [comment]
I think this one is fixed by https://github.com/dashpay/rs-tenderdash-abci/pull/49

If not, please reopen.
