### ISSUE TITLE
Missing updated .env.testnet

### ISSUE THREAD

**Issue by coolaj86** [dashpay/platform#1714]
`.env.testnet` at https://github.com/dashpay/platform/blob/v1.0-dev/packages/rs-drive-abci/.env.testnet is out of date and can't be used to run the latest dash-drive.

## Expected Behavior

Test config file should Just Work™

## Current Behavior

Errors about missing values. Guessing at the values doesn't work either.

```text
thread 'main' panicked at packages/rs-drive-abci/src/main.rs:314:13:
missing configuration option: VALIDATOR_SET_QUORUM_TYPE
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```text
missing configuration option: VALIDATOR_SET_QUORUM_TYPE
missing configuration option: CHAIN_LOCK_QUORUM_SIZE
```

## Possible Solution

🤷‍♂️

## Context

Trying to build, install, and run everything from source.

## Your Environment

Linux

Ubuntu 22.04 (LTS)

**Comment by shumkov** [comment]
Please update your PR.
