### ISSUE TITLE
doc: which services start in which order

### ISSUE THREAD

**Issue by coolaj86** [dashpay/platform#1745]
If you don't start the services in the right order, sometimes they just crash and don't restart (looking at you _tenderdash_).

Although that behavior is probably a bug... but right now I just want to document the relationships:

```
dashd        19999 (P2P), 19998 (RPC), 18009 (ZMQ)
├── dapi-core-streams 2510 (gRPC), <needs ZMQ>
├── drive
│   └── tenderdash 26656 (P2P, alt port for testnet?), 26657 (Tender RPC), 26658 (ABCI), 26660 (Prometheus), 36656 (seed peers?)
│       └── dapi-api 2501 (JSON RPC), 2500 (gRPC)
└── caddy (10000 testnet, 443 mainnet)
    └── envoy (3080 - arbitrary for comms with caddy)
```

Ports required for ProRegTx testnet:

| Dashcore P2P | 19999 |
| --- | --- |
| Tenderdash | 26656 (though I chose 26262) |
| HTTPS gRPC Bridge | 10000 |

**Comment by pshenmic** [comment]
What exactly do you see crashing. I think the right approach should  be that it waits until could connect and should not crash. Could you post some logs?

**Comment by coolaj86** [comment]
I believe tenderdash is the thing that's the most finicky. It was either that or drive.

Next time I see it happen I will post back the logs.

**Comment by shumkov** [comment]
Tenderdash is failing in some cases when Drive is falling. When Tenderdash is restarting, Drive is not. Please let us know if you see it behaves differently.
