### ISSUE TITLE
wallet forgets balance using nodeForage

### ISSUE THREAD

**Issue by dashameter** [dashpay/platform#183]
using `nodeforage` as a wallet adapter makes the wallet forget its balance

1. I sent 7 tDash to
2. I registered an identity first run with nodeforage (takes 5.5mins)
3. I registered an identity 2nd run with nodeforage (takes 3mins)
4. 3rd run to register an identity throws error:

` Error: Not enough balance (0) to cover burn amount of 10000`

when removing the `nodeforage` adapter the identity registers fine, when enabling it again the error returns. This has been replicated with a new `db.json` file and it happened again.

mnemonic also throws error on dashpay android wallet (reported via app)

nodeforage db: https://gist.github.com/dashameter/7192de242e54a4db533e08272f31e4b4
sample script: https://gist.github.com/dashameter/e755c3bfa9dc0cb8b112e6a77db97b2b

faucet transaction: https://testnet-insight.dashevo.org/insight/address/yX29oNG591LbqWWtDW2JTmL9pmAERmnswr

**Comment by dash-maverick** [comment]
Does it happen in localForage as well? (this will help to figure out where to look for the bug)
fyi @markin-io

**Comment by dash-maverick** [comment]
happening only with nodeForage (no issues with localForage fyi @markin-io )

**Comment by markin-io** [comment]
@dashameter please retest with v22.3

**Comment by dashameter** [comment]
waiting for testnet to be online for retest

**Comment by shumkov** [comment]
It was fixed
