### ISSUE TITLE
DAPIClientError: There is no connection config for network 'mainnet'

### ISSUE THREAD

**Issue by jojobyte** [dashpay/platform#2022]
Attempting to create a new client on `mainnet` throws an error.

## Expected Behavior
it should start a client connected to `mainnet`

## Current Behavior
`new Dash.Client({ network: 'mainnet' })` throws `DAPIClientError: There is no connection config for network 'mainnet'`

## Possible Solution
It appears https://github.com/dashpay/platform/blob/v1.0-dev/packages/js-dapi-client/lib/networkConfigs.js is missing any options for `mainnet`, adding some presumably would fix this, as the error comes from https://github.com/dashpay/platform/blob/v1.0-dev/packages/js-dapi-client/lib/dapiAddressProvider/createDAPIAddressProviderFromOptions.js#L101-L103

## Steps to Reproduce

1. `npm install dash`
2. Add `<script src="./node_modules/dash/dist/dash.min.js"></script>` to html
3. try to create a new client with `new Dash.Client({ network: 'mainnet' })`
4. See `DAPIClientError: There is no connection config for network 'mainnet'` error in console

## Context
Unable connect to `mainnet`.

## Your Environment
Version used:
```js
  "dependencies": {
    "dash": "^4.0.1"
  }
  ```

**Comment by shumkov** [comment]
It will be fixed in Platform 1.4
