### ISSUE TITLE
Storing ssl certificates in a configuration file config.json

### ISSUE THREAD

**Issue by konlag** [dashpay/platform#2027]
Storing ssl certificates in a configuration file config.json

Add function to dashmate setup, where the path to the certificate location will not be specified, keys will be entered instead

Example:

`
ssl: {
        enabled: false,
        provider: 'zerossl', 
        providerConfigs: { 
                zerossl: { 
                      apiKey: null, 
                      id: null }
                },
                file: {
                       key: 'KEY',
                       bundle: 'bundle'
                }
      }
`

**Comment by qwizzie** [comment]
Is this not already the case for config.json ? (under mainnet section !)

![Knipsel](https://github.com/user-attachments/assets/d8d2c8b3-ffca-4015-ae3b-821271dd48d6)

**Comment by mrssv** [comment]
Is there a way to indicate key and certificate file using dashmate commands?
It is possible to set ZeroSSL this way: 
dashmate config set platform.gateway.ssl.provider zerossl --config main
dashmate config set platform.gateway.ssl.providerConfigs.zerossl.apiKey xxxxxxxxxxxxxxxxxxxx  --config main

If i have self-signed certificate can i set it same way and what commands are needed for it? I did not find any option for this in code.

**Comment by pshenmic** [comment]
It is there in the setup, where you can supply your own keys bundle instead of zerossl. However, self signed certificates will not work, because you will need an certified IP Address certificate for the correct work of DAPI service.

<img width="754" alt="image" src="https://github.com/user-attachments/assets/dccc7407-13cc-480d-a30d-d350f578067d">
<img width="499" alt="image" src="https://github.com/user-attachments/assets/aede1a08-43db-4d9b-bf5a-4d6b166a45f5">

In case you want to switch from zerossl after you have already set it up, you can copy your cert files manually in the directory
```
~/.dashmate/mainnet/platform/gateway/ssl/bundle.crt
~/.dashmate/mainnet/platform/gateway/ssl/private.key
``` 

and do

```
dashmate config set platform.gateway.ssl.provider file
```

**Comment by konlag** [comment]
I have the option to issue my own certificates thawte (not self-signed).
I don't want to pay zerossl

It would be nice to specify the certificate in the config file, not just the path to the certificate....

**Comment by mrssv** [comment]
> It is there in the setup, where you can supply your own keys bundle instead of zerossl. However, self signed certificates will not work, because you will need an certified IP Address certificate for the correct work of DAPI service.
> 
> <img alt="image" width="754" src="https://private-user-images.githubusercontent.com/17009187/353915320-dccc7407-13cc-480d-a30d-d350f578067d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTUyNTYsIm5iZiI6MTcyMjU5NDk1NiwicGF0aCI6Ii8xNzAwOTE4Ny8zNTM5MTUzMjAtZGNjYzc0MDctMTNjYy00ODBkLWEzMGQtZDM1MGY1NzgwNjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDEwMzU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYzBlZTA5MzJlYzA0N2JmOWMxZmFkMWVmOGViNTZlYjNhMjRhYTVkOWI1ZWY4ZTMzNTNiMWM2MmM2YjMwZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.la_iiU2wNoStb1_JqROCLMj9MtxMN-NCiarTWw3hFgw">
> <img alt="image" width="499" src="https://private-user-images.githubusercontent.com/17009187/353915374-aede1a08-43db-4d9b-bf5a-4d6b166a45f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTUyNTYsIm5iZiI6MTcyMjU5NDk1NiwicGF0aCI6Ii8xNzAwOTE4Ny8zNTM5MTUzNzQtYWVkZTFhMDgtNDNkYi00ZDliLWJmNWEtNGQ2YjE2NmE0NWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDEwMzU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNThmOTdkNTFlYzNhOTEzYTEzNGMzNjU4MzM0MGYyMGY0MDdjM2M1ZWFiMGZmZTFkZDc2ZTFjNWMxNzc5YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.isqpQ-R2ktaaymI6A6r9czQAKF-0i4UPuC7Tzgd2bm8">
> In case you want to switch from zerossl after you have already set it up, you can copy your cert files manually in the directory
> 
> ```
> ~/.dashmate/mainnet/platform/gateway/ssl/bundle.crt
> ~/.dashmate/mainnet/platform/gateway/ssl/private.key
> ```
> 
> and do
> 
> ```
> dashmate config set platform.gateway.ssl.provider file
> ```
> 
> Let me know if that worked for you

Exactly, the 2nd option is what I was looking  for. It worked. Thank you very much!
