### ISSUE TITLE
 Ed25519 key is not generating automatically

### ISSUE THREAD

**Issue by gades** [dashpay/platform#2092]
## Expected Behavior

NEW KEY WILL BE AUTOMATICALLY GENERATED FOR YOU

## Current Behavior
Ed25519 is empty

## Possible Solution
workaround:
docker run --entrypoint /usr/bin/tenderdash --rm -ti dashpay/tenderdash gen-node-key

## Steps to Reproduce (for bugs)

1. dashmate setup
2. mainnet
3. evolution masternode 4000 DASH collateral
4. Is your masternode already registered? ‣ No
5. Dash Masternode Tool
6. Enter masternode operator private key
7. Enter Ed25519 node key is empty

![2024-08-29 17 23 29](https://github.com/user-attachments/assets/2dcf9cc7-4ce7-4f6c-b87c-473798c8d13a)

**Comment by pshenmic** [comment]
This is not a bug. In case you choose DMT as a registration option, you already have a node key, just paste it in

**Comment by gades** [comment]
In this case please use same names for keys (in dash mate it's ED25519 node key and in DMT - node key )

**Comment by shumkov** [comment]
Actually, it calls above as "Tenderdash node key" and "The node key".
