### ISSUE TITLE
feat: mainnet support for the js-sdk

### ISSUE THREAD

**Issue by thephez** [dashpay/platform#2109]
## Expected Behavior
The `mainnet` network type would be supported.

## Current Behavior
Currently, the JS SDK can only use mainnet if the `dapiAddresses` client option is used.

## Possible Solution
Update to work more like testnet where simply setting the network type is all that's required. Or provide a mainnet seed that could be used instead of hard-coding specific evonode addresses.

**Comment by shumkov** [comment]
JS SDK is updated https://github.com/dashpay/platform/pull/2146 and https://github.com/dashpay/platform/pull/2161

**Comment by shumkov** [comment]
The infrastructure team is working on testnet and miannet seed nodes.

**Comment by QuantumExplorer** [comment]
No code to write left. Closing for 1.4.
