### ISSUE TITLE
dapi: restart of tenderdash causes td version to be removed from status endpoint

### ISSUE THREAD

**Issue by shumkov** [dashpay/platform#2131]
Reported by @lklimek

**Comment by shumkov** [comment]
@lklimek I just tested. When I start tenderdash back DAPI reconnects to it. It might be some cache. In DAPI we cache getStatus response for 1 platform block. Could you please provide more information?

**Comment by lklimek** [comment]
Go to https://mnowatch.org/evonodes/ and notice that some nodes are missing version info of Tenderdash, some Drive.

In our testing, we have found that after panic in TD, DAPI stopped reporting version information. But we didn't spend time investigating this issue, just guessed this can be related to recent changes in DAPI.

**Comment by shumkov** [comment]
Thank for help with reproduction. Here is a fix https://github.com/dashpay/platform/pull/2155
