### ISSUE TITLE
Withdrawal Not Received in Testnet

### ISSUE THREAD

**Issue by LexxXell** [dashpay/platform#2302]
## Expected Behavior

When requesting a withdrawal on the Dash Platform testnet, the withdrawal should be processed successfully. The corresponding amount should be received in my Dash Electrum wallet, and the transaction should be visible on the blockchain.

## Current Behavior

I requested a withdrawal from the platform, and the withdrawal document exists and has moved to the status **completed**. However, the funds have not been received in my wallet, and there is no corresponding transaction visible on the blockchain.

Transaction of Credit Withdrawal
https://testnet.platform-explorer.com/transaction/3422E84DF3C422A2357634AC3504944FD14A9B6787EB29DCAA0FA84BA6CD6926

Block on Insight
http://insight.testnet.networks.dash.org:3001/insight/block/00000182164fb0022d9d547472741407febba2c251297959536161d61dc99c55

Document on Platform:
```js
{
  '$id': 'E1FZpGixJSXmAwwEtCxqHpGM3XeFyFKLdNSCQMmzFJko',
  '$ownerId': '8eTDkBhpQjHeqgbVeriwLeZr1tCa6yBGw76SckvD1cwc',
  amount: 4000000,
  coreFeePerByte: 1,
  outputScript: 'dqkUT5vx/UWS1NGHPxErcfXG2a3sicmIrA==',
  pooling: 0,
  status: 3,
  transactionIndex: 81,
  transactionSignHeight: 1131337,
  '$revision': 4,
  '$createdAt': 1730311760674,
  '$updatedAt': 1730328609682,
  ***
  '$dataContract': {
    '$format_version': '0',
    id: '4fJLR2GYTPFdomuTVvNy3VRrvWgvkKPzqehEBpNf2nk6',
    config: {
      '$format_version': '0',
      canBeDeleted: false,
      readonly: false,
      keepsHistory: false,
      documentsKeepHistoryContractDefault: false,
      documentsMutableContractDefault: true,
      documentsCanBeDeletedContractDefault: true,
      requiresIdentityEncryptionBoundedKey: null,
      requiresIdentityDecryptionBoundedKey: null
    },
    version: 1,
    ownerId: '11111111111111111111111111111111',
    schemaDefs: null,
    documentSchemas: { withdrawal: [Object] }
  },
  '$type': 'withdrawal'
}
```

## Possible Solution

There may be an issue with the withdrawal process not broadcasting the transaction to the network, or the transaction might be stuck and not included in any block. Investigating the transaction broadcasting and inclusion in blocks might help identify the problem.

## Steps to Reproduce (for bugs)

1. Request a withdrawal from the Dash Platform on testnet.
2. Verify that the withdrawal document exists and reaches the **completed** status.
3. Check the Dash Electrum wallet for incoming funds.
4. Look for the transaction on the testnet blockchain explorer.

## Context

I am testing the withdrawal functionality of the Dash Electrum wallet on testnet. This issue is preventing me from verifying that withdrawals are working correctly, which is essential for testing and development purposes.

**Comment by pshenmic** [comment]
@qwizzie I don't think thats the case, because the withdrawal transaction on platform happened on the 30 November, so I believe that should be enough for the completing in even in core chain.

Another thing, is it marked as COMPLETED in the withdrawal document, which I assume should be only when transaction successfully added in the Core chain.

We can see  transactionSignHeight is [1131337](http://insight.testnet.networks.dash.org:3001/insight/block/00000182164fb0022d9d547472741407febba2c251297959536161d61dc99c55), and transactionIndex: 81, but if we look at the block itself, there are no transaction except the coinbase one

**Comment by QuantumExplorer** [comment]
@pshenmic the sign height is not the block in which the transactions are in. It's the block that the Platform chain knows about when the withdrawal was authorized. It often is mined in the next block, as can be seen here:

https://blockexplorer.one/dash/testnet/address/yTaP3dCsRFLsdp7ZRXamNCrjUNNy5kHq9h

These withdrawals went through on testnet, I am closing this issue.
