### ISSUE TITLE
Define SDK use cases

### ISSUE THREAD

**Issue by shumkov** [dashpay/platform#2368]
We need to define who will be the users, what they will be building and for what platforms.

**Comment by shumkov** [comment]
https://docs.google.com/document/d/1OPdYsHV92lz0_BGB2Ac86qE8v7LTbD_g7QkTV4zwpi4/edit?tab=t.0

**Comment by blackmirrordesigner** [comment]
> https://docs.google.com/document/d/1OPdYsHV92lz0_BGB2Ac86qE8v7LTbD_g7QkTV4zwpi4/edit?tab=t.0

hello Ivan, may I pls get access to this file? curious to see who are the users, thanks

**Comment by TanteStefana** [comment]
I'd like to see this file as well.  It would go a long way to understanding our potential use cases for non-dev non-industry Dash community members, thanks :)
