### ISSUE TITLE
[Docs] Bad links / missing documentation

### ISSUE THREAD

**Issue by coolaj86** [dashpay/platform#251]
> You can see some [examples here](https://github.com/dashevo/platform/blob/master/docs/usage/examples.md).

Bad link: https://github.com/dashevo/platform/blob/master/docs/usage/examples.md

> More extensive documentation is available at https://dashevo.github.io/wallet-lib along with additional [examples & snippets](https://dashevo.github.io/wallet-lib/#/usage/examples).

No extensive documentation at https://dashevo.github.io/wallet-lib

No examples at https://dashevo.github.io/wallet-lib/#/usage/examples

**Comment by shumkov** [comment]
Not sure if we have those links anymore
