### ISSUE TITLE
Error: Assertion failed after funding a new wallet

### ISSUE THREAD

**Issue by HunterSides** [dashpay/platform#328]
## Issue Description
Receiving Error: Assertion when attempting to initialize Platform connection after funding a new wallet. 

## Mnemonic (non production)
{"mnemonic":"need grab endorse wine around fuel lawn flame tide section original boss"}

## Expected Behavior
After funding a new wallet with tDash a user should be able to initialize and connect to platform.

## Current Behavior
Throws Error: Assertion failed 
![image](https://user-images.githubusercontent.com/56932084/161655397-c95e1a2b-a093-49df-9711-8fd8698d7979.png)

## Steps to Reproduce (for bugs)
using this repo https://github.com/HunterSides/DDR-React

clone & npm install & npm start
open localhost:3000
open console & fund wallet address given
reload page after funding wallet

## Process Point Failure 
Platform connection initialization after funding given wallet address with tDash.

## Your Environment
@dash-incubator/dapp-sdk": "*"
Chrome & Firefox latest
Windows 10 64 bit
[Link to your project:](https://github.com/HunterSides/DDR-React)

**Comment by markin-io** [comment]
What is the version of `dash` SDK is used? Can you also provide a link to the repo with `@dash-incubator/dapp-sdk`

**Comment by HunterSides** [comment]
@markin-io  

Version 0.14.2 - https://github.com/dash-incubator/dapp-sdk 
Required as a dependency in package.json - https://github.com/HunterSides/DDR-React/blob/main/package.json 
Used here - https://github.com/HunterSides/DDR-React/blob/main/src/views/UploadPage.js

However I just rechecked and I'm not getting that error anymore instead I'm getting this one (I believe ICJR has already reported this specific one already)  
![image](https://user-images.githubusercontent.com/56932084/165861919-704b7885-8f2e-4b1f-9952-742a6a76f34a.png)

**Comment by markin-io** [comment]
@HunterSides please update to SDK v3.22.3 and test again

**Comment by SamKirby22** [comment]
@HunterSides - am I right in saying "it looks like ICJR needs to update the dapp sdk - Dash SDK package to v3.22.3 from v3.21.7"?

**Comment by ICJR** [comment]
@SamKirby22 Updated dash dependency to use the latest version. I am now seeing `RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.` after I fund a new testnet wallet with tDash.

**Comment by markin-io** [comment]
@ICJR @HunterSides thank you for the provided details and updates, we added this to our backlog

**Comment by markin-io** [comment]
@ICJR @HunterSides I launched the DDR-React project. Thank you for driving the Dash React App initiative, looks very promising!

I reproduced the issue and I think that the underlying problem is the fact that currently `dash` SDK requires an extra webpack configuration that provides Node.JS polyfills for browsers. We are currently working out a solution for proper bundling for the web without the additional configuration to improve the developer experience.

Having in mind that you are working with the CRA, you can not alter your webpack config without the eject (which is not desirable).

Here's what I suggest to do as a workaround for now:
- In `@dash-incubator/dapp-sdk` project:
  - Configure `webpack.typescript.config.js` to provide all required polyfills. This [comment](https://github.com/dashevo/platform/issues/395#issuecomment-1132571131) will help.
  - Add `"browser": "./dist/dapp.js"` to the `package.json` (This would make web-apps using dapp-sdk look for dapp.js bundle instead of the typescript build)
  - Build and publish to NPM
- Update `@dash-incubator/dapp-sdk` in `DDR-React` to a newer version and try running app again.

**Comment by ICJR** [comment]
@markin-io `dapp-sdk` is already providing the node polyfills during bundling https://github.com/dash-incubator/dapp-sdk/blob/main/webpack.typescript.config.js#L45 using `node-polyfill-webpack-plugin`

**Comment by markin-io** [comment]
@ICJR thank you. We're currently in progress with a proper SDK bundle for the web.

**Comment by markin-io** [comment]
@ICJR please update `dash` to `v0.22.12` and retest

**Comment by SamKirby22** [comment]
This one is for Hunter to check but would be good for ICJR to take a look too - as impacting both bounties.

**Comment by markin-io** [comment]
Aha, all right. @HunterSides @ICJR please also check out a new section in the documentation about using primitives https://github.com/dashevo/platform/tree/master/packages/js-dash-sdk#primitives-and-essentials

If you need more PlatformProtocol essentials exposed, please let us know. For the first iteration we only did ones that used by our internal platform test suite.

**Comment by ICJR** [comment]
@markin-io
![error](https://user-images.githubusercontent.com/12816631/173119509-e40a1766-a7ba-4d56-ae01-60cceceb1906.png)

Still receiving the errors above. I removed the node polyfill plugin provider, and updated dash npm to the latest version. Have you guys tested on another web app using just the dash npm package and a normal testnet platform connection? 

Asking so I can just tear everything apart on my end to find the issue.

**Comment by markin-io** [comment]
@ICJR yes, here it is 
[dash-react-starter-app.zip](https://github.com/dashevo/platform/files/8881003/dash-react-starter-app.zip)

**Comment by ICJR** [comment]
@markin-io 

Tried a few things still no luck

Received `More than one instance of dashcore-lib found. Please make sure that you are not mixing instances of classes of the different versions of dashcore.` used `npm dedupe` warning won't go away.

Also noticed the following endpoints 
/org.dash.platform.dapi.v0.Core/getStatus
/org.dash.platform.dapi.v0.Core/subscribeToTransactionsWithProofs

Constantly take 60186ms to respond throwing a 503/504 error.

**Comment by markin-io** [comment]
For now, to unblock your endeavor I might suggest using `dash` directly in your frontend app.

**Comment by HunterSides** [comment]
> @markin-io ![error](https://user-images.githubusercontent.com/12816631/173119509-e40a1766-a7ba-4d56-ae01-60cceceb1906.png)
> 
> Still receiving the errors above. I removed the node polyfill plugin provider, and updated dash npm to the latest version. Have you guys tested on another web app using just the dash npm package and a normal testnet platform connection?

Just reiterating ICJR here, I also still receive the errors after updating.

**Comment by markin-io** [comment]
@HunterSides thanks. Please try out one of the steps https://github.com/dashevo/platform/issues/328#issuecomment-1158683430

**Comment by HunterSides** [comment]
@markin-io @ICJR Attempting to use dapp-sdk as a git submodule gives me 
![image](https://user-images.githubusercontent.com/56932084/175996662-38c87a4e-bc23-4cab-918d-eb10c892cca0.png)
