### ISSUE TITLE
dashmate setup failed with error "Could not connect to Core RPC"

### ISSUE THREAD

**Issue by mayoreee** [dashpay/platform#365]
Running dashmate setup failed with the error "Could not connect to Core RPC"

## Expected Behavior

Successfully setup dashmate

## Current Behavior

Failed:
```
[SUCCESS] Create local group configs [7s]
[STARTED] Configure Core nodes
[STARTED] Task without title.
[STARTED] Starting seed node as a wallet
[FAILED] Could not connect to Core RPC
[FAILED] Could not connect to Core RPC
[FAILED] Could not connect to Core RPC
[FAILED] Could not connect to Core RPC
```

## Steps to Reproduce (for bugs)
`dashmate setup local masternode --verbose`

## Your Environment

* Version used: `dashmate v0.22.3`

**Comment by mayoreee** [comment]
Update: I tried a few things that turned out to be a **workaround** for this issue

1. Removed all associated `Containers` in Docker
2. Removed all associated `Volumes` in Docker
3. Ran `rm -r ~/.dashmate`
4. Ran `dashmate reset`
5. Setup dashmate afresh

The error did go away with these steps.

**Comment by SamKirby22** [comment]
Likely linked to: https://github.com/dashevo/platform/issues/389. Please review when retesting.
