### ISSUE TITLE
Dashmate uses outdated docker images for drive and dapi

### ISSUE THREAD

**Issue by pithuene** [dashpay/platform#378]
The dashmate version v0.22.7 pulls the Docker images `dashpay/dapi:0.22.0-dev.7` and `dashpay/drive:0.22.0-dev.7`.

## Expected Behavior
I would expect the dashmate version v0.22.7 to pull the Docker images `dashpay/dapi:0.22.7` and `dashpay/drive:0.22.7`.

## Possible Solution
Change default images in `packages/dashmate/configs/system/base.js` to the recent ones.

## Context
After an update of a testnet masternode using dashmate, the drive crashes because it fails to connect to MongoDB.
I believe this is a result of dashmate expecting to use grovedb, which is why it doesn't start a MongoDB, while the old drive at `0.22.0-dev.7` expects a MongoDB to be available.

## Your Environment
I have tested this on platform version `v0.22.6`, but it doesn't seem to be fixed in `v0.22.7`.

**Comment by pshenmic** [comment]
Dashmate now uses latest stable versions (dashpay/drive:0.22 for example)
