### ISSUE TITLE
dashd container runs at 100% cpu

### ISSUE THREAD

**Issue by dashameter** [dashpay/platform#380]
docker: dashpay/dashd:18.0.0.0-rc3

platform@v0.22.7

![image](https://user-images.githubusercontent.com/57665975/167084106-0c04dce5-516c-43cb-9666-cfaab2be01d7.png)

docker logs:
[dashd.log](https://github.com/dashevo/platform/files/8638225/dashd.log)

**Comment by dashameter** [comment]
reducing the amount of 
```
yarn dashmate wallet:mint 10 --address=<address> --config=local_seed
```

post `yarn setup` from 4 to 2 helps reducing the CPU load once the containers are started.

**Comment by markin-io** [comment]
@dashameter both `yarn setup` and `dashmate setup` should give you funded faucet private key:

Here's a log sample from `yarn setup` 
(hint: `yarn setup` also writes `FAUCET_PRIVATE_KEY` variable into the `platform-test-suite/.env`)
```
[SUCCESS] Configure Tenderdash nodes [8s]
[SUCCESS] Task without title. [33s]
Mint 100 Dash to faucet address
[STARTED] Generate 100 dash to address
[STARTED] Start Core
[SUCCESS] Start Core [3s]
[STARTED] Create a new address
[DATA] Address: yfHGYvokW15d7kcrAZJVQDTQpTugQmHMbd
[DATA] Private key: cS7pE2aVYTYsXr6DGxZmH4nKU5xhcd9Vhd57ri7fCe5pEiqSi843
[SUCCESS] Create a new address [0.0s]
[STARTED] Generate ≈100 dash to address
[TITLE] Generate ≈100 dash to address yfHGYvokW15d7kcrAZJVQDTQpTugQmHMbd
[DATA] 185.86656604 dash generated
[DATA] Generated 185.86656604 dash
[SUCCESS] Generate ≈100 dash to address yfHGYvokW15d7kcrAZJVQDTQpTugQmHMbd [0.0s]
[STARTED] Wait for balance to confirm
[DATA] 185.86656604 dash to confirm
```

After you obtained the faucet private key (^ cS7pE2aVYTYsXr6DGxZmH4nKU5xhcd9Vhd57ri7fCe5pEiqSi843), use it to instantiate SDK/Wallet and send Layer 1 funding transaction to the newly created HD wallet.

Use these functions as a reference for usage:
https://github.com/dashevo/platform/blob/v0.23-dev/packages/platform-test-suite/lib/test/createFaucetClient.js#L33
https://github.com/dashevo/platform/blob/v0.23-dev/packages/platform-test-suite/lib/test/createClientWithFundedWallet.js

**Comment by dashameter** [comment]
machine spec: i7 10th gen, 40GB Ram, Ubuntu

**Comment by markin-io** [comment]
@ogabrielides @PastaPastaPasta  hey guys. May I have a bit of your attention there? Perhaps you have any thoughts about why it could happen, or what is the proper way of debugging/profiling this.

**Comment by SamKirby22** [comment]
@ogabrielides @PastaPastaPasta hi both, this issue has significant impact. Any update on this?

**Comment by thephez** [comment]
When I observed this issue it was primarily in some llmq threads. Udjin said that this PR had some fixes that might resolve it: https://github.com/dashpay/dash/pull/4890. That is in a recent Core RC (7) which isn't being used by dashmate yet (https://github.com/dashevo/platform/blob/v0.23-dev/packages/dashmate/configs/system/base.js#L36).
