### ISSUE TITLE
drive always restarting because public keys are missing

### ISSUE THREAD

**Issue by ghost** [dashpay/platform#386]
drive restarts because 4 public keys are missing.
## Current Behavior

After setup a masternode with dashmate these keys are missing. Because of that drive is always restarting.

DPNS_MASTER_PUBLIC_KEY
DASHPAY_MASTER_PUBLIC_KEY
FEATURE_FLAGS_MASTER_PUBLIC_KEY
MASTERNODE_REWARD_SHARES_MASTER_PUBLIC_KEY

## Steps to Reproduce (for bugs)

1. Start dashmate with testnet and masternode selected for setup
2. Followed the guide from https://docs.dash.org/en/stable/masternodes/setup-testnet.html#manual-installation for masternode registration
3. Typed "docker ps" after a successful registration and have a look at status by dash_masternode_testnet_drive_abci_1
4. "docker ps <container id of dash_masternode_testnet_drive_abci_1>" tells that 4 public keys are missing

## Your Environment

* Version used: dashmate version 0.22.7 linux-x64 node-v16.14.2 
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop, server, or mobile): Ubuntu 20.04.3 LTS
* Link to your project:

**Comment by Sotatek-HoangDo** [comment]
anyone have a solution for this yet ?

**Comment by pshenmic** [comment]
I am not sure we can mix up dashmate setup with manual installations. Also, it seems that manual installation guide is out of date, and may show unexpected results. Better to stick to dashmate at the moment

**Comment by thephez** [comment]
The docs were updated a few weeks after this PR was opened (https://github.com/dashpay/docs/pull/133) and worked at the time they were merged as I understand it. @jaboski could correct me if that's not accurate.

**Comment by shumkov** [comment]
It's not actual anymore. Use `dashmate setup`
