### ISSUE TITLE
dashmate group start gets stuck in the local_seed node startup

### ISSUE THREAD

**Issue by mayoreee** [dashpay/platform#447]
dashmate group start get stuck in local_seed node startup
## Expected Behavior

Successfully start group nodes

## Current Behavior

`dashmate group:start --verbose`
```
[STARTED] Start local nodes
[STARTED] Starting nodes
[STARTED] Starting local_1 node
[STARTED] Starting local_2 node
[STARTED] Starting local_3 node
[STARTED] Starting local_seed node
[STARTED] Check node is not started
[STARTED] Check node is not started
[STARTED] Check node is not started
[STARTED] Check node is not started
[SUCCESS] Check node is not started [0.5s]
[STARTED] Start services
[SUCCESS] Check node is not started [0.5s]
[STARTED] Start services
[SUCCESS] Check node is not started [0.5s]
[STARTED] Start services
[SUCCESS] Check node is not started [0.9s]
[STARTED] Start services
[SUCCESS] Start services [1s]
[STARTED] Force nodes to sync
[DATA] 0.00% complete
[DATA] 0.00% complete
[DATA] 0.00% complete
[DATA] 0.00% complete
[DATA] 100.00% complete
[SUCCESS] Force nodes to sync [0.5s]
[SUCCESS] Starting local_seed node [2s]
```

Remained stuck on the last line and didn’t startup the nodes

## Steps to Reproduce (for bugs)

`dashmate group:start —verbose`

**Comment by dashameter** [comment]
For me the workaround to solve this error was to disable my vpn client. Even though the vpn client did not cause a problem on Ubuntu, on Debian it prevented the local_seed not to be reached.

**Comment by pshenmic** [comment]
I have seen this couple times when you try to restart local network via stop and start commands (without cleaning and setup)
