### ISSUE TITLE
Fix error message when running dashmate start without setup

### ISSUE THREAD

**Issue by pshenmic** [dashpay/platform#487]
## Expected Behavior

Running `yarn dashmate start` on fresh setup (without setup command) should throw readable and understandable error message
## Current Behavior

On fresh setup it throws because dashmate configuration is not setup yet:
✖ externalIp option is not set in testnet config

## Possible Solution

Check that there are no configuration yet and throw clear error message

## Steps to Reproduce (for bugs)

1. Clean everything out, including ~/.dashmate
2. yarn dashmate start

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop, server, or mobile):
* Link to your project:

**Comment by shumkov** [comment]
Fixed in v0.24
