### ISSUE TITLE
feat(dashmate): do not render template configs in dashmate configuration folder

### ISSUE THREAD

**Issue by pshenmic** [dashpay/platform#546]
## Expected Behavior

Template configurations are not rendered in dashmate configuration folder

## Current Behavior

Base and local config dirs are rendered, but is not used at all - they are only used to render subsequent configurations, like mainnet, testnet, local_1 and so on. Template configs should not be created in the dashmate folder dir

## Possible Solution

Do not render it when configs are being saved in the dashmate configuration folder

## Steps to Reproduce (for bugs)

1. dashmate setup
2. check ~/.dashmate for base and local folder existence
3.
4.

## Your Environment

* Version used: 0.23.0-dev.10
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node.JS v16.14.2
* Operating System and version (desktop, server, or mobile): Apple M1
* Link to your project:

**Comment by shumkov** [comment]
Technically you can use these configs in the same way as you are using mainnet or testnet. They behave the same. Not sure we want to create a specific behavior for these two.
