### ISSUE TITLE
Random password generator

### ISSUE THREAD

**Issue by strophy** [dashpay/platform#93]
We should use random passwords for RPC to increase security. We currently use the following username and password:
```
rpcuser=dashrpc
rpcpassword=password
```

It's not possible to randomly generate passwords in docker-compose because the files are supposed to be idempotent. My previous attempt at implementing this generated a [random password](https://github.com/strophy/dash-masternode-docker/blob/master/dash.sh#L7) when templating the config file, can we do something similar here with a helper script maybe, or is there another approach?

**Comment by shumkov** [comment]
It's done
