### ISSUE TITLE
feat(dashmate): Owner / Operator modes for dashmate

### ISSUE THREAD

**Issue by thephez** [dashpay/platform#939]
Thoughts based on a conversation with splawik...

## Current Behavior
Currently dashmate requires both the owner/voting/payout addresses AND the BLS/Platform private keys. When the MN is owned by one person and hosted by another (a frequent situation), neither party typically will have all of that info. 

## Possible Solution
It could be helpful to have 2 modes:
 - Owner mode: would ask for the BLS _public_ key and the Platform node ID instead of the private keys which are not required for constructing the protx register command. This mode would really do nothing but assemble the protx.
 - Operator mode: would not ask for owner info (collater tx, owner/voting/payout keys, etc.) but would just set up the services that run on the masternode

**Comment by shumkov** [comment]
> Owner mode: would ask for the BLS public key and the Platform node ID instead of the private keys which are not required for constructing the protx register command. This mode would really do nothing but assemble the protx.

So, in this case `dashmate setup` just show a command to register a HPMN but do not actually setup a node?

> Operator mode: would not ask for owner info (collater tx, owner/voting/payout keys, etc.) but would just set up the services that run on the masternode

I think we already have this "mode", you just choice "Masternode is already registered - Yes", isn't?

**Comment by thephez** [comment]
> > Operator mode: would not ask for owner info (collater tx, owner/voting/payout keys, etc.) but would just set up the services that run on the masternode
> 
> I think we already have this "mode", you just choice "Masternode is already registered - Yes", isn't?

Good point. You're correct about this one :see_no_evil: 

> > Owner mode: would ask for the BLS public key and the Platform node ID instead of the private keys which are not required for constructing the protx register command. This mode would really do nothing but assemble the protx.
> 
> So, in this case `dashmate setup` just show a command to register a HPMN but do not actually setup a node?
> 
Yes, that's what I was thinking. And allowing them to just do it with the _public_ BLS key. But it's probably not worth doing this unless people ask for it. As I think about it more I imagine a lot of people will use [Dash Masternode Tool](https://github.com/Bertrand256/dash-masternode-tool) for that via its wizard (once HPMN support is there).

![image](https://user-images.githubusercontent.com/8145677/234314273-59386705-0150-428d-bdf9-0c6140a9d60d.png)

**Comment by shumkov** [comment]
@thephez do you think it's still actual?

**Comment by thephez** [comment]
> @thephez do you think it's still actual?

@shumkov, we should see what @splawik21 thinks? It may not be something that's important any more.

**Comment by splawik21** [comment]
@thephez It doesn't have much importance imo tbh.
If someone makes it on his own, that person has all the privkeys and can register himself.
If someone uses a service, the service provider gives necessary steps to register the MN/Evonode.
Not sure why complicating it even more.

**Comment by thephez** [comment]
Closing based on feedback. This issue is no longer relevant.
