### ISSUE TITLE
Containers do not accept new settings when restarted

### ISSUE THREAD

**Issue by strophy** [dashpay/platform#98]
Any changes to config that affect the configuration of a container will not be applied until the container is destroyed and recreated. 

## Expected Behavior
Changing config and restarting containers should apply config changes

## Current Behavior
Changing config and restarting containers keeps the old config

## Possible Solution
It should be possible to force docker-compose to rebuild the containers with new settings from images when restarting

## Steps to Reproduce (for bugs)

1. Start node
2. Change settings (e.g. log level)
3. Restart node
4. New settings are not applied

## Context
Cannot reconfigure nodes

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop, server, or mobile):
* Link to your project:

**Comment by shumkov** [comment]
Fixed
