### ISSUE TITLE
dashmate: wrapped protx text creates error

### ISSUE THREAD

**Issue by thephez** [dashpay/platform#983]
## Expected Behavior
The `dash-cli` registration command can be copied/pasted and run without error

## Current Behavior
On Ubuntu if a line of the command wraps due to terminal size, the wrapped line is treated as 2 lines when copied. See the image below and the copied text after that as an example.

![image](https://user-images.githubusercontent.com/8145677/234646052-6a271fa3-49ab-4da4-a69a-485b9b86c1d6.png)

Text as copied (`a1cdeff0c2c` should be part of the preceding line):
```
              dash-cli protx register_hpmn \
                    42e42808717d29aeb52ff887c5e2f89644ee8821f81e8aa17df98a8a9d42e005 \
                    1 \
                    66.135.17.16:19999 \
                    ycA3BZhR4iuriu7GtyNrFyQZGyhdWnLayB \
                    877b9c567469ecced854a663192b0d4b1e2b1edeb30ca260e220aa9e20e088a91897f1755647cca4ffb3c
a1cdeff0c2c \
                    ye8PP4SXXmoU7AWBJrDzjL41zXrKeToU9v \
                    0.00 \
                    yYT41qwj6CwsU3rW2TjcKmsA3ASaqvWTUW \
                    4f7a54074cabd0502594962837f6041783935968 \
                    36656 \
                    1443
```

## Steps to Reproduce (for bugs)
1. Run dashmate setup
2. Resize terminal so it is narrower than the widest out line
3. Copy the wrapped text and see that the long line is split

## Context
When the dash-cli command is pasted into a terminal to run, it throws a "command not found" error when it tries treating the wrapped text as a new command.

![image](https://user-images.githubusercontent.com/8145677/234647174-9898f1e0-322c-45ef-85ca-bf73d9128665.png)

## Your Environment

* Version used: Dashmate 0.24.0-dev.25
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node v16.20.0
* Operating System and version (desktop, server, or mobile): Ubuntu 22.04

**Comment by shumkov** [comment]
Noted

**Comment by thephez** [comment]
Looks like #996 fixes this for me on Ubuntu :+1:
