### ISSUE TITLE
Reset should recreate collateral and protx for local node

### ISSUE THREAD

**Issue by strophy** [dashpay/platform#99]
Resetting a local node will need to recreate the collateral and protx before the system is usable again. We should recreate this when running reset on local, or alternatively automate something like `mn reset && mn setup local`.

## Expected Behavior
Node should be immediately startable after reset

## Current Behavior
Node needs to run through setup local again before becoming startable after reset, and config is different.

## Steps to Reproduce (for bugs)

1. Spin up local node
2. mn reset
3. mn start

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop, server, or mobile):
* Link to your project:

**Comment by shumkov** [comment]
It's not actual anymore
